# Generated by Django 4.2.1 on 2023-05-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.CharField(default='reciever', max_length=225),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='sender', max_length=255),
        ),
    ]
