export const CHATLIST_REQUEST='CHATLIST_REQUEST'
export const CHATLIST_SUCCESS='CHATLIST_SUCCESS'
export const CHATLIST_FAIL='CHATLIST_FAIL'


export const MAINCHAT_REQUEST='MAINCHAT_REQUEST'
export const MAINCHAT_SUCCESS='MAINCHAT_SUCCESS'
export const MAINCHAT_FAIL='MAINCHAT_FAIL'


export const ONLINE_REQUEST='ONLINE_REQUEST'
export const ONLINE_SUCCESS='ONLINE_SUCCESS'
export const ONLINE_FAIL='ONLINE_FAIL'